config/routes.rb
Rails.application.routes.draw do
  namespace 'buses' do
    get 'user_id/:user_id', action: 'show_by_user_id', as: 'show_by_user_id'
    get ':id/latlng', action: 'latlng', as: 'latlng'
  end
  resources :buses

  namespace 'bus_stops' do
    get 'closest', action: 'closest', as: 'closest'
    get 'state_district_data', action: 'state_district_data', as: 'state_district_data'
    post 'lat_lng', action: 'lat_lng', as: 'lat_lng'
  end
  resources :bus_stops

  devise_scope :user do
    get 'users/conductors', to: 'users/registrations#conductors'
    devise_for :users, :controllers => {:registrations => 'users/registrations', :sessions => 'users/sessions'}
  end

  root to: 'welcome#welcome'

end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :latlng, :edit, :update, :destroy]

  acts_as_token_authentication_handler_for User, :only => [:new, :edit, :create, :update, :destroy]

  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all.compact
    if params.has_key? :src and params.has_key? :dst
      src_id = params[:src].to_i
      dst_id = params[:dst].to_i
      buses_to_delete = []
      @buses.each do |bus|
        bus_stop_ids = bus.reaches.pluck(:bus_stop_id)
        buses_to_delete.push(bus) if !(bus_stop_ids.include? src_id and bus_stop_ids.include? dst_id) or bus[:status] == "off"
      end
      buses_to_delete.each do |bus|
        @buses.delete(bus)
      end
    end
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  #GET /buses/1/latlng.json
  def latlng
  end

  # GET /buses/user_id/1.json
  def show_by_user_id
    begin
      set_bus_by_user_id
    rescue
      render json: { error: "Bus not found" }
    end
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus, status = Bus.addNewBus(params)

    respond_to do |format|
      if status == true
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    @bus, status = Bus.updateBus(@bus, params)
    respond_to do |format|
      if status == true
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
      @route = @bus.reaches.collect{|reach| reach.bus_stop.attributes.merge(reach.attributes.extract!("stop_num"))}
      @conductor = @bus.user.attributes.extract!("id", "first_name", "last_name")
    end

    def set_bus_by_user_id
      @bus = Bus.find_by_user_id(params[:user_id])
      @route = @bus.reaches.collect{|reach| reach.bus_stop.attributes.merge(reach.attributes.extract!("stop_num"))}
      @conductor = @bus.user.attributes.extract!("id", "first_name", "last_name")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      params.require(:bus).permit(:bus_num, :registration_num, :status, :latitude, :longitude, :capacity, :seat_avail, :ac_nonac, :user_id, :bus_stop_id)
    end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_form.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<%= bootstrap_form_for(@bus, :html => {:onsubmit => "return false"}) do |f| %>
  <% if @bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% @bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-4">
    <div class="form-group">
      <label class="control-label" for="bus_bus_num">Bus Number</label>
      <input class="form-control" type="text" name="bus[bus_num]" id="bus_bus_num" required ng-model="bus.bus_num"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_registration_num">Registration Number</label>
      <input class="form-control" type="text" name="bus[registration_num]" id="bus_registration_num" required ng-model="bus.registration_num"/>
    </div>
    <!--<div class="form-group">
      <label class="control-label" for="bus_status">Status</label>
      <input class="form-control" type="text" name="bus[status]" id="bus_status" value="off" ng-model="bus.status" ng-show="false"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_latitude">Latitude</label>
      <input class="form-control" type="number" step="any" name="bus[latitude]" id="bus_latitude" value=23.384096 ng-model="bus.latitude" string-to-number ng-show="false"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_longitude">Longitude</label>
      <input class="form-control" type="number" step="any" name="bus[longitude]" id="bus_longitude" value=77.497747 ng-model="bus.longitude" string-to-number ng-show="false"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_seat_avail">Seat avail</label>
      <input class="form-control" type="hidden" name="bus[seat_avail]" id="bus_seat_avail" value=0 ng-model="bus.seat_avail"/>
    </div>-->
    <div class="form-group">
      <label class="control-label" for="bus_capacity">Capacity</label>
      <input class="form-control" type="number" min="0" name="bus[capacity]" id="bus_capacity" required ng-model="bus.capacity"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_ac_nonac">AC/Non-AC</label>
      <select class="form-control" name="bus[ac_nonac]" id="bus_ac_nonac" required ng-model="bus.ac_nonac">
        <option value="" hidden>Select type</option>
        <option value="ac">AC</option>
        <option value="nonac">Non-AC</option>
      </select>
    </div>
    <!--<div class="form-group">
      <label class="control-label" for="bus_bus_stops">Bus Stops</label>
      <select class="form-control" name="bus[bus_stops]" id="bus_bus_stops" ng-model="busStop" ng-options="bus_stop.name group by bus_stop.state for bus_stop in busStops track by bus_stop.id">
        <option value="" hidden>Select Bus Stop</option>
      </select>
    </div>-->
    <div class="form-group">
      <label class="control-label" for="bus_conductor">Conductor</label>
      <ui-select name="bus[conductor]" id="bus_conductor" ng-model="bus.conductor" theme="bootstrap" close-on-select="true" title="Choose conductor">
        <ui-select-match class="ui-select-match" placeholder="Select or search a conductor in the list...">{{$select.selected.first_name + ' ' + $select.selected.last_name}}</ui-select-match>
        <ui-select-choices class="ui-select-choices" repeat="conductor in conductors | filter: $select.search">
          <div ng-bind-html="conductor.first_name + ' ' + conductor.last_name | highlight: $select.search"></div>
        </ui-select-choices>
      </ui-select>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_bus_stops">Bus Stops</label>
      <ui-select multiple name="bus[bus_stops]" id="bus_bus_stops" ng-model="bus.route" theme="bootstrap" close-on-select="false" title="Choose bus stop">
        <ui-select-match class="ui-select-match" placeholder="Select or search a bus stop in the list...">{{$item.name}}</ui-select-match>
        <ui-select-choices class="ui-select-choices" repeat="bus_stop in busStops | filter: $select.search">
          <div ng-bind-html="bus_stop.name | highlight: $select.search"></div>
          <small ng-bind-html="bus_stop.district + ' ,' + bus_stop.state | highlight: $select.search"></small>
        </ui-select-choices>
      </ui-select> 
    </div>
    <button type="button" class="btn btn-success" ng-click="submit()">Submit</button>
    <button type="submit" class="submit" hidden>Submit</button>
  </div>
  <div class="col-sm-4">
    <div style='width:800px;'>
      <div id="map" style='width:800px; height:400px;'></div>
    </div>
  </div>

<!--
  <div class="field">
    <%= f.text_field :bus_num %>
  </div>
  <div class="field">
    <%= f.text_field :registration_num %>
  </div>
  <div class="field">
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.number_field :latitude %>
  </div>
  <div class="field">
    <%= f.number_field :longitude %>
  </div>
  <div class="field">
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.number_field :seat_avail %>
  </div>
  <div class="field">
    <%= f.text_field :ac_nonac %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
-->
<% end %>

app/views/buses/edit.html.erb
<div class="container">
  <h1>Editing Bus</h1>

  <div ng-controller="editBus">
    <%= render 'form' %>
  </div>

</div>
<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<div class="container">
<h1>Listing Buses</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Bus num</th>
      <th>Registration num</th>
      <th>Status</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Capacity</th>
      <th>Ac nonac</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= bus.bus_num %></td>
        <td><%= bus.registration_num %></td>
        <td><%= bus.status %></td>
        <td><%= bus.latitude %></td>
        <td><%= bus.longitude %></td>
        <td><%= bus.capacity %></td>
        <td><%= bus.ac_nonac %></td>
        <td><%= link_to 'Show', bus, method: :get %></td>
        <td><%= link_to 'Edit', edit_bus_path(bus), method: :get %></td>
        <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/buses/new.html.erb
<div class="container">
  <h1>New Bus</h1>

  <div ng-controller="newBus">
    <%= render 'form' %>
  </div>
</div>  
<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<div class="container">
      	<div class="col-sm-3"></div>
	<div class="col-sm-6">
	<div class="panel panel-default">
		<div class="panel-heading"><strong>Bus Details</strong></div>
		<div class="panel-body">
			
			<label>Bus num:</label>
			<p>
			  <%= @bus.bus_num %>
			</p>

			  <label>Registration num:</label>
			<p>
			  <%= @bus.registration_num %>
			</p>

			  <label>Status:</label>
			<p>
			  <%= @bus.status %>
			</p>

			  <label>Latitude:</label>
			<p>
			  <%= @bus.latitude %>
			</p>

			  <label>Longitude:</label>
			<p>
			  <%= @bus.longitude %>
			</p>

			  <label>Capacity:</label>
			<p>
			  <%= @bus.capacity %>
			</p>

			  <label>Seat avail:</label>
			<p>
			  <%= @bus.seat_avail %>
			</p>

			  <label>Ac nonac:</label>
			<p>
			  <%= @bus.ac_nonac %>
			</p>
		</div>
	</div>
	</div>
	<div class="col-sm-3"></div>

<%= link_to 'Edit', edit_bus_path(@bus), method: :get %> |
<%= link_to 'Back', buses_path %>
</div>