config/routes.rb
Rails.application.routes.draw do
  namespace 'buses' do
    get 'user_id/:user_id', action: 'show_by_user_id', as: 'show_by_user_id'
    get ':id/latlng', action: 'latlng', as: 'latlng'
  end
  resources :buses

  namespace 'bus_stops' do
    get 'closest', action: 'closest', as: 'closest'
    get 'state_district_data', action: 'state_district_data', as: 'state_district_data'
    post 'lat_lng', action: 'lat_lng', as: 'lat_lng'
  end
  resources :bus_stops

  devise_scope :user do
    get 'users/conductors', to: 'users/registrations#conductors'
    devise_for :users, :controllers => {:registrations => 'users/registrations', :sessions => 'users/sessions'}
  end

  root to: 'welcome#welcome'

end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  has_many :reaches, :dependent => :delete_all
  has_many :buses, through: :reaches

  validates :name, uniqueness: true 

  acts_as_mappable :default_units => :kms,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

  require 'json'

  def self.get_city_district_hash
     data = File.read('public/state_district.json')
     JSON.parse(data).symbolize_keys 
  end

  def self.get_lat_lng_from_address address
    include Geokit::Geocoders
    location = MultiGeocoder.geocode(address)
    location.hash
  end
end

app/controllers/bus_stops_controller.rb
class BusStopsController < ApplicationController
  before_action :set_bus_stop, only: [:show, :edit, :update, :destroy]

  acts_as_token_authentication_handler_for User, :only => [:new, :edit, :create, :update, :destroy]

  require 'json'

  # GET /bus_stops
  # GET /bus_stops.json
  def index
    @bus_stops = BusStop.all
    if params.has_key? :state
      @bus_stops = @bus_stops.where(:state => params[:state]).order(:district)
    end
  end

  # GET /bus_stops/closest
  def closest
    @bus_stop = BusStop.closest(:origin => [params[:lat], params[:lng]])[0]
  end

  # GET /bus_stops/1
  # GET /bus_stops/1.json
  def show
  end

  # GET /bus_stops/new
  def new
    @bus_stop = BusStop.new
  end

  # GET /bus_stops/1/edit
  def edit
  end

  # POST /bus_stops
  # POST /bus_stops.json
  def create
    @bus_stop = BusStop.new(bus_stop_params)

    respond_to do |format|
      if @bus_stop.save
        format.html { redirect_to @bus_stop, notice: 'Bus stop was successfully created.' }
        format.json { render :show, status: :created, location: @bus_stop }
      else
        format.html { render :new }
        format.json { render json: @bus_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_stops/1
  # PATCH/PUT /bus_stops/1.json
  def update
    respond_to do |format|
      if @bus_stop.update(bus_stop_params)
        format.html { redirect_to @bus_stop, notice: 'Bus stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_stop }
      else
        format.html { render :edit }
        format.json { render json: @bus_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_stops/1
  # DELETE /bus_stops/1.json
  def destroy
    @bus_stop.destroy
    respond_to do |format|
      format.html { redirect_to bus_stops_url, notice: 'Bus stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /bus_stops/state_district_data.json
  def state_district_data
    @state_district_hash = BusStop.get_city_district_hash
  end

  # POST /bus_stops/lat_long.json
  def lat_lng
    @location = BusStop.get_lat_lng_from_address params[:address]
    puts @location
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_stop
      @bus_stop = BusStop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_stop_params
      params.require(:bus_stop).permit(:name, :street, :district, :state, :latitude, :longitude)
    end
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/views/bus_stops/_form.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<%= bootstrap_form_for(@bus_stop) do |f| %>
  <% if @bus_stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus_stop.errors.count, "error") %> prohibited this bus_stop from being saved:</h2>

      <ul>
      <% @bus_stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-4">
    <div class="form-group">
      <label class="control-label" for="bus_stop_name">Name</label>
      <input class="form-control" type="text" name="bus_stop[name]" id="bus_stop_name" required ng-model="busStop['name']"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_stop_street">Street</label>
      <input class="form-control" type="text" name="bus_stop[street]" id="bus_stop_street" required ng-model="busStop['street']"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_stop_state">State</label>
      <select class="form-control" name="bus_stop[state]" id="bus_stop_state" required ng-model="busStop['state']" ng-options="state for state in states track by state">
         <option value="" style="display:none">Select State</option>
      </select>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_stop_district">District</label>
      <select class="form-control" name="bus_stop[district]" id="bus_stop_district" required ng-model="busStop['district']" ng-options="district for district in stateDistrictData[busStop['state']] track by district">
        <option value="" style="display:none">Select District</option>
      </select>
    </div>
    <div class="form-group"i>
      <label class="control-label" for="bus_stop_latitude">Latitude</label>
      <input class="form-control" type="number" step="any" name="bus_stop[latitude]" id="bus_stop_latitude" readonly required ng-model="busStop['latitude']" string-to-number/>
    </div>
    <div class="form-group">
      <label class="control-label" for="bus_stop_longitude">Longitude</label>
      <input class="form-control" type="number" step="any" name="bus_stop[longitude]" id="bus_stop_longitude" readonly required ng-model="busStop['longitude']" string-to-number/>
    </div>
    <div class="col-sm-6">
      <button type="button" class="btn btn-success" ng-click="getLatLng()">Get Latitude-Longitude</button>
    </div>
    <div class="col-sm-4">
    <%= f.submit %>
    </div>
  </div>
  <div class="col-sm-4">
    <div style='width:800px;'>
      <div id="map" style='width:800px; height:400px;'></div>
    </div>
  </div>

<% end %>

app/views/bus_stops/edit.html.erb
<div class="container">
  <h1>Editing Bus Stop</h1>

  <div ng-controller="editBusStop">
    <%= render 'form' %>
  </div>

</div>
<%= link_to 'Show', @bus_stop %> |
<%= link_to 'Back', bus_stops_path %>

app/views/bus_stops/index.html.erb
<div class="container">
<h1>Listing Bus Stops</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>District</th>
      <th>State</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bus_stops.each do |bus_stop| %>
      <tr>
        <td><%= bus_stop.name %></td>
        <td><%= bus_stop.street %></td>
        <td><%= bus_stop.district %></td>
        <td><%= bus_stop.state %></td>
        <td><%= bus_stop.latitude %></td>
        <td><%= bus_stop.longitude %></td>
        <td><%= link_to 'Show', bus_stop, method: :get %></td>
        <td><%= link_to 'Edit', edit_bus_stop_path(bus_stop), method: :get %></td>
        <td><%= link_to 'Destroy', bus_stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/bus_stops/new.html.erb
<div class="container">
  <h1>New Bus Stop</h1>

  <div ng-controller="newBusStop">
    <%= render 'form' %>
  </div>
</div>
<%= link_to 'Back', bus_stops_path %>

app/views/bus_stops/show.html.erb
<div class="container">
	<div class="col-sm-3"></div>
	<div class="col-sm-6">
	<div class="panel panel-default">
		<div class="panel-heading"><strong>Bus Stop Details</strong></div>
		<div class="panel-body">
			  <label>Name:</label>
			<p>
			  <%= @bus_stop.name %>
			</p>

			  <label>Street:</label>
			<p>
			  <%= @bus_stop.street %>
			</p>

			  <label>District:</label>
			<p>
			  <%= @bus_stop.district %>
			</p>

			  <label>State:</label>
			<p>
			  <%= @bus_stop.state %>
			</p>

			  <label>Latitude:</label>
			<p>
			  <%= @bus_stop.latitude %>
			</p>

			  <label>Longitude:</label>
			<p>
			  <%= @bus_stop.longitude %>
			</p>
		</div>
	</div>
	</div>
	<div class="col-sm-3"></div>
<%= link_to 'Edit', edit_bus_stop_path(@bus_stop), method: :get %> |
<%= link_to 'Back', bus_stops_path %>
<div>