config/routes.rb
Rails.application.routes.draw do
  namespace 'buses' do
    get 'user_id/:user_id', action: 'show_by_user_id', as: 'show_by_user_id'
    get ':id/latlng', action: 'latlng', as: 'latlng'
  end
  resources :buses

  namespace 'bus_stops' do
    get 'closest', action: 'closest', as: 'closest'
    get 'state_district_data', action: 'state_district_data', as: 'state_district_data'
    post 'lat_lng', action: 'lat_lng', as: 'lat_lng'
  end
  resources :bus_stops

  devise_scope :user do
    get 'users/conductors', to: 'users/registrations#conductors'
    devise_for :users, :controllers => {:registrations => 'users/registrations', :sessions => 'users/sessions'}
  end

  root to: 'welcome#welcome'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bus App</a>
    </div>
    <% if can? :manage, :app %>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
        	<%= link_to "Home", buses_path, :method => "get" %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Buses<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Index", buses_path, :method => "get" %></li>
                <li class="divider"></li>
            <li><%= link_to "New Bus", new_bus_path, :method => "get" %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Bus Stops<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Index", bus_stops_path, :method => "get" %></li>
                <li class="divider"></li>
            <li><%= link_to "New Bus Stop", new_bus_stop_path, :method => "get" %></li>
          </ul>
        </li>
      </ul>

      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= current_user.first_name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Account Settings", edit_user_registration_path, :method => "get" %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => "delete" %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!--/.nav-collapse -->
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusappServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app='busApp' style="padding-top: 60px">

<%= render "layouts/header" %>

<% if notice %>	
<div class="alert alert-success">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<strong>Note!</strong> <%= notice %>	
</div>
<% end %>

<% if alert %>	
<div class="alert alert-warning">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<strong>Error!</strong> <%= alert %>	
</div>
<% end %>

<%= yield %>

</body>
</html>